var level_1 = 
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [{ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "ladrillo_azul", movement: true}, {ladrillo: "ladrillo_azul", movement: true},], // Primera fila
        [{ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true}, {ladrillo: "ladrillo_rojo", movement: true},], // Segunda fila
        [{ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true}, {ladrillo: "ladrillo_amarillo", movement: true},], // Tercera fila
        [{ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "ladrillo_purpura", movement: true}, {ladrillo: "ladrillo_purpura", movement: true},], // Cuarta fila
        [{ladrillo: "ladrillo_naranja", movement: true}, {ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},{ladrillo: "ladrillo_naranja", movement: true},], // Quinta fila
        [{ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true}, {ladrillo: "ladrillo_rosa", movement: true},],// Sexta fila
        [{ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "ladrillo_verde", movement: true}, {ladrillo: "", movement: true},], // Septima fila
        //[{ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false}, {ladrillo: "ladrillo_indestructible", movement: false},], // Octava fila
        //[{ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false}, {ladrillo: "ladrillo_regenerativo", movement: false},], // Novena fila
        //[{ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false}, {ladrillo: "ladrillo_duro", movement: false},] // Decima fila
    ]
}
/* var level_1 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
        ],
        [
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
        ],
        [
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
        ],
        [
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
            { ladrillo: "ladrillo_celeste", movement: false },
        ],
        [
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_regenerativo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_regenerativo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
        ],
    ]
} */

var level_2 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
        ],
        [
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
        ],
        [
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
        ],
        [
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
    ]
}

var level_3 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [],
        [],
        [],
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: true },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: true },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        
    ]
}

var level_4 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
    ]
}

var level_5 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [], 
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_purpura", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_purpura", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
    ]
}

var level_6 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [],
        [],
        [],
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
        ],
        [
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
        ],
        [
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
        ],
    ]
}

var level_7 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [],
        [
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_morado", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
        ],
    ]
}

var level_8 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_regenerativo", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_rojoRosado", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "ladrillo_regenerativo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: true },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: true },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_regenerativo", movement: false },
        ],
    ]
}

var level_9 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_marron", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_annil", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
        ],
        
    ]
}

var level_10 =
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_verde", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_amarillo", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azulClaro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rosa", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: true },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_naranja", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_azul", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_purpura", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_rojo", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_indestructible", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
        [
            { ladrillo: "", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "ladrillo_duro", movement: false },
            { ladrillo: "", movement: false },
        ],
    ]
}