var level_1 = 
{
    enemy_type: "",
    background: "",
    music: "",
    ladrillos: [
        [{ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false}, {ladrillo: "ladrillo_azul", movement: false},], // Primera fila
        [{ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false}, {ladrillo: "ladrillo_rojo", movement: false},], // Segunda fila
        [{ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false}, {ladrillo: "ladrillo_amarillo", movement: false},], // Tercera fila
        [{ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false}, {ladrillo: "ladrillo_purpura", movement: false},], // Cuarta fila
        [{ladrillo: "ladrillo_naranja", movement: false}, {ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},{ladrillo: "ladrillo_naranja", movement: false},], // Quinta fila
        [{ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false}, {ladrillo: "ladrillo_rosa", movement: false},],// Sexta fila
        [{ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false}, {ladrillo: "ladrillo_verde", movement: false},], // Septima fila
    ]
}