var nivel1 =
{
    fondo: "fondo1-3",
    borde: "borde1-3",
    techoInferior: "techoInferior1-3",
    techoAdicional: "techoAdicional1-3",
    musica: "",
    burbuja: [
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaVe", color: "Ve" },
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaVe", color: "Ve" },
        ],
        [
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAm", color: "Am" },
        ],
        [
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAm", color: "Am" },
        ],
    ]
}
var nivel2 =
{
    fondo: "fondo1-3",
    borde: "borde1-3",
    techoInferior: "techoInferior1-3",
    techoAdicional: "techoAdicional1-3",
    musica: "",
    burbuja: [
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaGr", color: "Gr" },
            { burbuja: "burbujaGr", color: "Gr" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            " ",
            " ",
        ],
    ]
}
var nivel3 =
{
    fondo: "fondo1-3",
    borde: "borde1-3",
    techoInferior: "techoInferior1-3",
    techoAdicional: "techoAdicional1-3",
    musica: "",
    burbuja: [
        [
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
        ],
        [
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaAm", color: "Am" },
        ],
        [
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaRo", color: "Ro" },
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
            " ",
        ],
    ]
}
var nivel4 =
{
    fondo: "fondo4-6",
    borde: "borde4-6",
    techoInferior: "techoInferior4-6",
    techoAdicional: "techoAdicional4-6",
    musica: "",
    burbuja: [
        [
            " ",
            { burbuja: "burbujaGr", color: "Gr" },
            { burbuja: "burbujaGr", color: "Gr" },
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAz", color: "Az" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            " ",
        ],
    ]
}
var nivel5 =
{
    fondo: "fondo4-6",
    borde: "borde4-6",
    techoInferior: "techoInferior4-6",
    techoAdicional: "techoAdicional4-6",
    musica: "",
    burbuja: [
        [
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
        ],
        [
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            { burbuja: "burbujaAz", color: "Az" },
        ],
        [
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
        ],
        [
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
            " ",
        ],
    ]
}
var nivel6 =
{
    fondo: "fondo4-6",
    borde: "borde4-6",
    techoInferior: "techoInferior4-6",
    techoAdicional: "techoAdicional4-6",
    musica: "",
    burbuja: [
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaMo", color: "Mo" },
        ],
        [
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            " ",
            { burbuja: "burbujaBl", color: "Bl" },
            " ",
            { burbuja: "burbujaAm", color: "Am" },
        ],
        [
            " ",
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAz", color: "Az" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            { burbuja: "burbujaBl", color: "Bl" },
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
        ],
        [
            { burbuja: "burbujaBl", color: "Bl" },
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            " ",
            { burbuja: "burbujaAz", color: "Az" },
        ],
        [
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
        ],
    ]
}
var nivel7 =
{
    fondo: "fondo7-9",
    borde: "borde7-9",
    techoInferior: "techoInferior7-9",
    techoAdicional: "techoAdicional7-9",
    musica: "",
    burbuja: [
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
        ],
        [
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
        ],
        [
            " ",
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaMo", color: "Mo" },
            " ",
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaAz", color: "Az" },
            " ",
        ],
    ]
}
var nivel8 =
{
    fondo: "fondo7-9",
    borde: "borde7-9",
    techoInferior: "techoInferior7-9",
    techoAdicional: "techoAdicional7-9",
    musica: "",
    burbuja: [
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
        ],
        [
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaMo", color: "Mo" },
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
        ],
        [
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaBl", color: "Bl" },
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaMo", color: "Mo" },
        ],
    ]
}
var nivel9 =
{
    fondo: "fondo7-9",
    borde: "borde7-9",
    techoInferior: "techoInferior7-9",
    techoAdicional: "techoAdicional7-9",
    musica: "",
    burbuja: [
        [
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaNa", color: "Na" },
        ],
        [
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaNa", color: "Na" },
        ],
        [
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaGr", color: "Gr" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaMo", color: "Mo" },
        ],
        [
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            " ",
            " ",
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaMo", color: "Mo" },
        ],
        [
            { burbuja: "burbujaNa", color: "Na" },
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaRo", color: "Ro" },
        ],
        [
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaGr", color: "Gr" },
            " ",
            " ",
            " ",
            " ",
            " ",
        ],
        [
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            " ",
            " ",
            " ",
            " ",
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaVe", color: "Ve" },
            " ",
            " ",
        ],
    ]
}
var nivel10 =
{
    fondo: "fondo10-12",
    borde: "borde10-12",
    techoInferior: "techoInferior10-12",
    techoAdicional: "techoAdicional10-12",
    musica: "",
    burbuja: [
        [
            { burbuja: "burbujaGr", color: "Gr" },
            " ",
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaGr", color: "Gr" },
        ],
        [
            { burbuja: "burbujaGr", color: "Gr" },
            " ",
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaGr", color: "Gr" },
        ],
        [
            { burbuja: "burbujaGr", color: "Gr" },
            " ",
            " ",
            " ",
            " ",
            " ",
            " ",
            { burbuja: "burbujaRo", color: "Ro" },
        ],
        [
            { burbuja: "burbujaRo", color: "Ro" },
            { burbuja: "burbujaAz", color: "Az" },
            { burbuja: "burbujaAm", color: "Am" },
            { burbuja: "burbujaVe", color: "Ve" },
            { burbuja: "burbujaNa", color: "Na" },
            { burbuja: "burbujaMo", color: "Mo" },
            { burbuja: "burbujaGr", color: "Gr" },
        ],
    ]
}